version: "3.8"

networks:
  infra:

services:

############### UI ####################################
  app:
    build: ./ui
    volumes:
      - ./ui:/django
    ports:
      - 8003:8003
    image: app:ui
    container_name: ui
    depends_on:
      mysql:
        condition: service_healthy
    command: python manage.py runserver 0.0.0.0:8003
    networks:
      - infra
######################## Created Deamon ###########################################
  createddeamon:
    build: .
    volumes:
      - .:/deamon
      - ./ssl:/usr/lib/ssl/
    image: deamon:created
    container_name: createddeamon
    restart: on-failure
    depends_on:
      mysql:
        condition: service_healthy
    command: ["python3", "./pubsub/createdeamon.py"]
    networks:
      - infra
########################Controlled Deamon ##################################
  controlleddeamon:
    build: .
    volumes:
      - .:/deamon
      - ./ssl:/usr/lib/ssl/
    image: deamon:controlled
    container_name: controlleddeamon
    restart: on-failure
    depends_on:
      mysql:
        condition: service_healthy
    command: ["python3", "./pubsub/controlleddeamon.py"]
    networks:
      - infra
########################### Confirmed Deamon ##############################
  confimeddeamon:
    build: .
    volumes:
      - .:/deamon
      - ./ssl:/usr/lib/ssl/
    image: deamon:confimed
    container_name: confimeddeamon
    restart: on-failure
    depends_on:
      mysql:
        condition: service_healthy
    command: ["python3", "./pubsub/confirmeddeamon.py"]
    networks:
      - infra 
########################### Database Execute ##############################
  dbexecutedeamon:
    build: .
    volumes:
      - .:/deamon
      - ./ssl:/usr/lib/ssl/
    image: deamon:dbe
    container_name: dbexecutedeamon
    restart: on-failure
    depends_on:
      mysql:
        condition: service_healthy
    command: ["python3", "./pubsub/dbexecutedeamon.py"]
    networks:
      - infra 
############################# Mysql #################################
  mysql:
    image: mysql
    container_name: mysql
    restart: unless-stopped
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
      - ./ssl:/usr/lib/ssl/
    ports:
      - "33077:3306"
    environment:
      MYSQL_DATABASE: compta
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    networks:
      - infra
############################# phpMyadmin ###################
  pma:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    restart: always
    ports:
      - '8888:80'
    environment:
      PMA_HOST: mysql
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - infra

########################### RabbitMQ ############################