# Generated by Django 3.2.12 on 2023-07-16 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Engagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created', models.CharField(max_length=20)),
                ('controlled', models.CharField(max_length=20)),
                ('confirmed', models.CharField(max_length=20)),
                ('canceled', models.BooleanField(default=False)),
            ],
        ),
    ]
